package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1



/**
 * TblActividadDestino generated by hbm2java
 */
public class TblActividadDestino  implements java.io.Serializable {


     private TblActividadDestinoId id;
     private TblActividad tblActividad;
     private TblDestino tblDestino;

    public TblActividadDestino() {
    }

    public TblActividadDestino(TblActividadDestinoId id, TblActividad tblActividad, TblDestino tblDestino) {
       this.id = id;
       this.tblActividad = tblActividad;
       this.tblDestino = tblDestino;
    }
   
    public TblActividadDestinoId getId() {
        return this.id;
    }
    
    public void setId(TblActividadDestinoId id) {
        this.id = id;
    }
    public TblActividad getTblActividad() {
        return this.tblActividad;
    }
    
    public void setTblActividad(TblActividad tblActividad) {
        this.tblActividad = tblActividad;
    }
    public TblDestino getTblDestino() {
        return this.tblDestino;
    }
    
    public void setTblDestino(TblDestino tblDestino) {
        this.tblDestino = tblDestino;
    }




}


