package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblActividad generated by hbm2java
 */
public class TblActividad  implements java.io.Serializable {


     private Integer idActividad;
     private String nombreActividad;
     private String descripcionActividad;
     private String recomendaciones;
     private Set tblActividadDestinos = new HashSet(0);

    public TblActividad() {
    }

	
    public TblActividad(String nombreActividad) {
        this.nombreActividad = nombreActividad;
    }
    public TblActividad(String nombreActividad, String descripcionActividad, String recomendaciones, Set tblActividadDestinos) {
       this.nombreActividad = nombreActividad;
       this.descripcionActividad = descripcionActividad;
       this.recomendaciones = recomendaciones;
       this.tblActividadDestinos = tblActividadDestinos;
    }
   
    public Integer getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(Integer idActividad) {
        this.idActividad = idActividad;
    }
    public String getNombreActividad() {
        return this.nombreActividad;
    }
    
    public void setNombreActividad(String nombreActividad) {
        this.nombreActividad = nombreActividad;
    }
    public String getDescripcionActividad() {
        return this.descripcionActividad;
    }
    
    public void setDescripcionActividad(String descripcionActividad) {
        this.descripcionActividad = descripcionActividad;
    }
    public String getRecomendaciones() {
        return this.recomendaciones;
    }
    
    public void setRecomendaciones(String recomendaciones) {
        this.recomendaciones = recomendaciones;
    }
    public Set getTblActividadDestinos() {
        return this.tblActividadDestinos;
    }
    
    public void setTblActividadDestinos(Set tblActividadDestinos) {
        this.tblActividadDestinos = tblActividadDestinos;
    }




}


