package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblDestino generated by hbm2java
 */
public class TblDestino  implements java.io.Serializable {


     private Integer idDestino;
     private String nombreDestino;
     private String descripcionDestino;
     private Set tblViajes = new HashSet(0);
     private Set tblActividadDestinos = new HashSet(0);

    public TblDestino() {
    }

	
    public TblDestino(String nombreDestino) {
        this.nombreDestino = nombreDestino;
    }
    public TblDestino(String nombreDestino, String descripcionDestino, Set tblViajes, Set tblActividadDestinos) {
       this.nombreDestino = nombreDestino;
       this.descripcionDestino = descripcionDestino;
       this.tblViajes = tblViajes;
       this.tblActividadDestinos = tblActividadDestinos;
    }
   
    public Integer getIdDestino() {
        return this.idDestino;
    }
    
    public void setIdDestino(Integer idDestino) {
        this.idDestino = idDestino;
    }
    public String getNombreDestino() {
        return this.nombreDestino;
    }
    
    public void setNombreDestino(String nombreDestino) {
        this.nombreDestino = nombreDestino;
    }
    public String getDescripcionDestino() {
        return this.descripcionDestino;
    }
    
    public void setDescripcionDestino(String descripcionDestino) {
        this.descripcionDestino = descripcionDestino;
    }
    public Set getTblViajes() {
        return this.tblViajes;
    }
    
    public void setTblViajes(Set tblViajes) {
        this.tblViajes = tblViajes;
    }
    public Set getTblActividadDestinos() {
        return this.tblActividadDestinos;
    }
    
    public void setTblActividadDestinos(Set tblActividadDestinos) {
        this.tblActividadDestinos = tblActividadDestinos;
    }




}


