package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1



/**
 * TblImagen generated by hbm2java
 */
public class TblImagen  implements java.io.Serializable {


     private Integer idImagen;
     private TblViaje tblViaje;
     private String nombreImagen;

    public TblImagen() {
    }

    public TblImagen(TblViaje tblViaje, String nombreImagen) {
       this.tblViaje = tblViaje;
       this.nombreImagen = nombreImagen;
    }
   
    public Integer getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(Integer idImagen) {
        this.idImagen = idImagen;
    }
    public TblViaje getTblViaje() {
        return this.tblViaje;
    }
    
    public void setTblViaje(TblViaje tblViaje) {
        this.tblViaje = tblViaje;
    }
    public String getNombreImagen() {
        return this.nombreImagen;
    }
    
    public void setNombreImagen(String nombreImagen) {
        this.nombreImagen = nombreImagen;
    }




}


