package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1



/**
 * TblReservacion generated by hbm2java
 */
public class TblReservacion  implements java.io.Serializable {


     private Integer idReservacion;
     private TblUsuario tblUsuario;
     private TblViaje tblViaje;
     private int cancelado;

    public TblReservacion() {
    }

    public TblReservacion(TblUsuario tblUsuario, TblViaje tblViaje, int cancelado) {
       this.tblUsuario = tblUsuario;
       this.tblViaje = tblViaje;
       this.cancelado = cancelado;
    }
   
    public Integer getIdReservacion() {
        return this.idReservacion;
    }
    
    public void setIdReservacion(Integer idReservacion) {
        this.idReservacion = idReservacion;
    }
    public TblUsuario getTblUsuario() {
        return this.tblUsuario;
    }
    
    public void setTblUsuario(TblUsuario tblUsuario) {
        this.tblUsuario = tblUsuario;
    }
    public TblViaje getTblViaje() {
        return this.tblViaje;
    }
    
    public void setTblViaje(TblViaje tblViaje) {
        this.tblViaje = tblViaje;
    }
    public int getCancelado() {
        return this.cancelado;
    }
    
    public void setCancelado(int cancelado) {
        this.cancelado = cancelado;
    }




}


