package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblRuta generated by hbm2java
 */
public class TblRuta  implements java.io.Serializable {


     private Integer idRuta;
     private String nombreRuta;
     private Set tblTransportes = new HashSet(0);

    public TblRuta() {
    }

    public TblRuta(String nombreRuta, Set tblTransportes) {
       this.nombreRuta = nombreRuta;
       this.tblTransportes = tblTransportes;
    }
   
    public Integer getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(Integer idRuta) {
        this.idRuta = idRuta;
    }
    public String getNombreRuta() {
        return this.nombreRuta;
    }
    
    public void setNombreRuta(String nombreRuta) {
        this.nombreRuta = nombreRuta;
    }
    public Set getTblTransportes() {
        return this.tblTransportes;
    }
    
    public void setTblTransportes(Set tblTransportes) {
        this.tblTransportes = tblTransportes;
    }




}


