package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblRol generated by hbm2java
 */
public class TblRol  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;
     private String descripcionRol;
     private Set tblUsuarios = new HashSet(0);

    public TblRol() {
    }

	
    public TblRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public TblRol(String nombreRol, String descripcionRol, Set tblUsuarios) {
       this.nombreRol = nombreRol;
       this.descripcionRol = descripcionRol;
       this.tblUsuarios = tblUsuarios;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public String getDescripcionRol() {
        return this.descripcionRol;
    }
    
    public void setDescripcionRol(String descripcionRol) {
        this.descripcionRol = descripcionRol;
    }
    public Set getTblUsuarios() {
        return this.tblUsuarios;
    }
    
    public void setTblUsuarios(Set tblUsuarios) {
        this.tblUsuarios = tblUsuarios;
    }




}


