package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblTransporte generated by hbm2java
 */
public class TblTransporte  implements java.io.Serializable {


     private Integer idTransporte;
     private TblRuta tblRuta;
     private Integer numeroPasajeros;
     private String nombreTransporte;
     private String descripcionTransporte;
     private Set tblViajes = new HashSet(0);

    public TblTransporte() {
    }

	
    public TblTransporte(TblRuta tblRuta) {
        this.tblRuta = tblRuta;
    }
    public TblTransporte(TblRuta tblRuta, Integer numeroPasajeros, String nombreTransporte, String descripcionTransporte, Set tblViajes) {
       this.tblRuta = tblRuta;
       this.numeroPasajeros = numeroPasajeros;
       this.nombreTransporte = nombreTransporte;
       this.descripcionTransporte = descripcionTransporte;
       this.tblViajes = tblViajes;
    }
   
    public Integer getIdTransporte() {
        return this.idTransporte;
    }
    
    public void setIdTransporte(Integer idTransporte) {
        this.idTransporte = idTransporte;
    }
    public TblRuta getTblRuta() {
        return this.tblRuta;
    }
    
    public void setTblRuta(TblRuta tblRuta) {
        this.tblRuta = tblRuta;
    }
    public Integer getNumeroPasajeros() {
        return this.numeroPasajeros;
    }
    
    public void setNumeroPasajeros(Integer numeroPasajeros) {
        this.numeroPasajeros = numeroPasajeros;
    }
    public String getNombreTransporte() {
        return this.nombreTransporte;
    }
    
    public void setNombreTransporte(String nombreTransporte) {
        this.nombreTransporte = nombreTransporte;
    }
    public String getDescripcionTransporte() {
        return this.descripcionTransporte;
    }
    
    public void setDescripcionTransporte(String descripcionTransporte) {
        this.descripcionTransporte = descripcionTransporte;
    }
    public Set getTblViajes() {
        return this.tblViajes;
    }
    
    public void setTblViajes(Set tblViajes) {
        this.tblViajes = tblViajes;
    }




}


