package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblUsuario generated by hbm2java
 */
public class TblUsuario  implements java.io.Serializable {


     private Integer idUsuario;
     private TblRol tblRol;
     private String nombreUsuario;
     private String contrasenia;
     private String primerNombre;
     private String primerApellido;
     private String correoElectronico;
     private Set tblReservacions = new HashSet(0);

    public TblUsuario() {
    }

	
    public TblUsuario(TblRol tblRol, String nombreUsuario, String contrasenia, String primerNombre, String primerApellido, String correoElectronico) {
        this.tblRol = tblRol;
        this.nombreUsuario = nombreUsuario;
        this.contrasenia = contrasenia;
        this.primerNombre = primerNombre;
        this.primerApellido = primerApellido;
        this.correoElectronico = correoElectronico;
    }
    public TblUsuario(TblRol tblRol, String nombreUsuario, String contrasenia, String primerNombre, String primerApellido, String correoElectronico, Set tblReservacions) {
       this.tblRol = tblRol;
       this.nombreUsuario = nombreUsuario;
       this.contrasenia = contrasenia;
       this.primerNombre = primerNombre;
       this.primerApellido = primerApellido;
       this.correoElectronico = correoElectronico;
       this.tblReservacions = tblReservacions;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TblRol getTblRol() {
        return this.tblRol;
    }
    
    public void setTblRol(TblRol tblRol) {
        this.tblRol = tblRol;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Set getTblReservacions() {
        return this.tblReservacions;
    }
    
    public void setTblReservacions(Set tblReservacions) {
        this.tblReservacions = tblReservacions;
    }




}


