package pojos;
// Generated 10-abr-2016 21:48:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblViaje generated by hbm2java
 */
public class TblViaje  implements java.io.Serializable {


     private Integer idViaje;
     private TblDestino tblDestino;
     private TblTransporte tblTransporte;
     private String nombreViaje;
     private Date fechaInicio;
     private Date fechaFin;
     private Set tblReservacions = new HashSet(0);
     private Set tblImagens = new HashSet(0);

    public TblViaje() {
    }

	
    public TblViaje(String nombreViaje, Date fechaInicio, Date fechaFin) {
        this.nombreViaje = nombreViaje;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public TblViaje(TblDestino tblDestino, TblTransporte tblTransporte, String nombreViaje, Date fechaInicio, Date fechaFin, Set tblReservacions, Set tblImagens) {
       this.tblDestino = tblDestino;
       this.tblTransporte = tblTransporte;
       this.nombreViaje = nombreViaje;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.tblReservacions = tblReservacions;
       this.tblImagens = tblImagens;
    }
   
    public Integer getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(Integer idViaje) {
        this.idViaje = idViaje;
    }
    public TblDestino getTblDestino() {
        return this.tblDestino;
    }
    
    public void setTblDestino(TblDestino tblDestino) {
        this.tblDestino = tblDestino;
    }
    public TblTransporte getTblTransporte() {
        return this.tblTransporte;
    }
    
    public void setTblTransporte(TblTransporte tblTransporte) {
        this.tblTransporte = tblTransporte;
    }
    public String getNombreViaje() {
        return this.nombreViaje;
    }
    
    public void setNombreViaje(String nombreViaje) {
        this.nombreViaje = nombreViaje;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set getTblReservacions() {
        return this.tblReservacions;
    }
    
    public void setTblReservacions(Set tblReservacions) {
        this.tblReservacions = tblReservacions;
    }
    public Set getTblImagens() {
        return this.tblImagens;
    }
    
    public void setTblImagens(Set tblImagens) {
        this.tblImagens = tblImagens;
    }




}


