package pojos;
// Generated 04-mar-2016 23:09:34 by Hibernate Tools 4.3.1



/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private Integer idViaje;
     private String nombreViaje;
     private String descripcionViaje;
     private Reservacion reservacion;

    public Viaje() {
    }

    public Viaje(String nombreViaje, String descripcionViaje, Reservacion reservacion) {
       this.nombreViaje = nombreViaje;
       this.descripcionViaje = descripcionViaje;
       this.reservacion = reservacion;
    }
   
    public Integer getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(Integer idViaje) {
        this.idViaje = idViaje;
    }
    public String getNombreViaje() {
        return this.nombreViaje;
    }
    
    public void setNombreViaje(String nombreViaje) {
        this.nombreViaje = nombreViaje;
    }
    public String getDescripcionViaje() {
        return this.descripcionViaje;
    }
    
    public void setDescripcionViaje(String descripcionViaje) {
        this.descripcionViaje = descripcionViaje;
    }
    public Reservacion getReservacion() {
        return this.reservacion;
    }
    
    public void setReservacion(Reservacion reservacion) {
        this.reservacion = reservacion;
    }




}


